packages:
  - apps/*
  - packages/*
overrides:
  'fast-uri@': 3.1.5
  'nanoid@': 3.3.18
  deepmerge-ts: 8.0.2
verifyDepsBeforeRun: false
allowBuilds:
  '@prisma/engines': true
  cpu-features: false
  esbuild: true
  msgpackr-extract: false
  prisma: true
  protobufjs: false
  sharp: true
  ssh2: false
minimumReleaseAgeExclude:
  - deepmerge-ts@8.0.2
