CREATE TYPE "audit_actor_kind" AS ENUM ('HUMAN', 'SERVICE_PRINCIPAL', 'SYSTEM');
CREATE TYPE "audit_outcome" AS ENUM ('SUCCEEDED', 'DENIED', 'FAILED');

CREATE TABLE "audit_events" (
  "id" UUID NOT NULL PRIMARY KEY,
  "recorded_sequence" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "action_code" VARCHAR(120) NOT NULL,
  "contract_version" INTEGER NOT NULL,
  "source_module" VARCHAR(80) NOT NULL,
  "occurred_at" TIMESTAMPTZ(6) NOT NULL,
  "recorded_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "actor_kind" "audit_actor_kind" NOT NULL,
  "actor_user_id" UUID,
  "actor_service_principal_id" UUID,
  "system_actor_code" VARCHAR(120),
  "session_id" UUID,
  "authority_role_assignment_id" UUID,
  "authority_role_template_code" VARCHAR(80),
  "authority_role_template_version" INTEGER,
  "authority_capability_code" VARCHAR(120),
  "authority_policy_id" VARCHAR(160),
  "authority_scope_type" "access_scope_type",
  "authority_scope_id" UUID,
  "institution_id" UUID,
  "assurance" "authentication_assurance",
  "approval_request_id" UUID,
  "resource_type" VARCHAR(80) NOT NULL,
  "resource_id" VARCHAR(200) NOT NULL,
  "reason_code" VARCHAR(80),
  "reason_text" VARCHAR(500),
  "outcome" "audit_outcome" NOT NULL,
  "failure_code" VARCHAR(120),
  "request_id" VARCHAR(200),
  "correlation_id" VARCHAR(200) NOT NULL,
  "operation_id" VARCHAR(200) NOT NULL,
  "source_version" BIGINT,
  "before_summary" JSONB,
  "after_summary" JSONB,
  "corrects_audit_event_id" UUID,
  CONSTRAINT "audit_events_recorded_sequence_key" UNIQUE ("recorded_sequence"),
  CONSTRAINT "audit_events_operation_key" UNIQUE ("source_module", "action_code", "operation_id"),
  CONSTRAINT "audit_events_correction_fkey" FOREIGN KEY ("corrects_audit_event_id") REFERENCES "audit_events"("id") ON DELETE RESTRICT,
  CONSTRAINT "audit_events_action_check" CHECK ("action_code" ~ '^[a-z][a-z0-9-]*(\.[a-z][a-z0-9-]*)+$' AND position('*' IN "action_code") = 0),
  CONSTRAINT "audit_events_contract_version_check" CHECK ("contract_version" > 0),
  CONSTRAINT "audit_events_source_module_check" CHECK ("source_module" IN ('identity', 'access', 'audit')),
  CONSTRAINT "audit_events_actor_shape_check" CHECK (
    ("actor_kind" = 'HUMAN' AND "actor_user_id" IS NOT NULL AND "actor_service_principal_id" IS NULL AND "system_actor_code" IS NULL)
    OR ("actor_kind" = 'SERVICE_PRINCIPAL' AND "actor_user_id" IS NULL AND "actor_service_principal_id" IS NOT NULL AND "system_actor_code" IS NULL AND "session_id" IS NULL)
    OR ("actor_kind" = 'SYSTEM' AND "actor_user_id" IS NULL AND "actor_service_principal_id" IS NULL AND "system_actor_code" IS NOT NULL AND "session_id" IS NULL)
  ),
  CONSTRAINT "audit_events_system_actor_code_check" CHECK ("system_actor_code" IS NULL OR ("system_actor_code" = btrim("system_actor_code") AND "system_actor_code" ~ '^[A-Za-z0-9][A-Za-z0-9._:-]*$')),
  CONSTRAINT "audit_events_authority_template_check" CHECK (("authority_role_template_code" IS NULL) = ("authority_role_template_version" IS NULL)),
  CONSTRAINT "audit_events_authority_scope_check" CHECK (("authority_scope_type" IS NULL) = ("authority_scope_id" IS NULL)),
  CONSTRAINT "audit_events_authority_version_check" CHECK ("authority_role_template_version" IS NULL OR "authority_role_template_version" > 0),
  CONSTRAINT "audit_events_resource_check" CHECK ("resource_type" ~ '^[A-Z][A-Z0-9_]*$' AND "resource_id" = btrim("resource_id") AND length("resource_id") > 0),
  CONSTRAINT "audit_events_reason_check" CHECK (("reason_code" IS NULL OR ("reason_code" = btrim("reason_code") AND length("reason_code") > 0)) AND ("reason_text" IS NULL OR ("reason_text" = btrim("reason_text") AND length("reason_text") > 0 AND position(E'\n' IN "reason_text") = 0))),
  CONSTRAINT "audit_events_failure_check" CHECK (("outcome" = 'SUCCEEDED' AND "failure_code" IS NULL) OR ("outcome" <> 'SUCCEEDED' AND "failure_code" IS NOT NULL)),
  CONSTRAINT "audit_events_reference_check" CHECK ("correlation_id" = btrim("correlation_id") AND length("correlation_id") > 0 AND "operation_id" = btrim("operation_id") AND length("operation_id") > 0),
  CONSTRAINT "audit_events_source_version_check" CHECK ("source_version" IS NULL OR "source_version" >= 0),
  CONSTRAINT "audit_events_before_summary_check" CHECK ("before_summary" IS NULL OR (jsonb_typeof("before_summary") = 'object' AND octet_length("before_summary"::text) <= 8192)),
  CONSTRAINT "audit_events_after_summary_check" CHECK ("after_summary" IS NULL OR (jsonb_typeof("after_summary") = 'object' AND octet_length("after_summary"::text) <= 8192)),
  CONSTRAINT "audit_events_not_self_correction_check" CHECK ("corrects_audit_event_id" IS NULL OR "corrects_audit_event_id" <> "id")
);

CREATE INDEX "audit_events_resource_timeline_idx" ON "audit_events"("resource_type", "resource_id", "recorded_sequence" DESC, "id" DESC);
CREATE INDEX "audit_events_human_actor_timeline_idx" ON "audit_events"("actor_user_id", "recorded_sequence" DESC, "id" DESC) WHERE "actor_user_id" IS NOT NULL;
CREATE INDEX "audit_events_service_actor_timeline_idx" ON "audit_events"("actor_service_principal_id", "recorded_sequence" DESC, "id" DESC) WHERE "actor_service_principal_id" IS NOT NULL;
CREATE INDEX "audit_events_institution_timeline_idx" ON "audit_events"("institution_id", "recorded_sequence" DESC, "id" DESC) WHERE "institution_id" IS NOT NULL;
CREATE INDEX "audit_events_correlation_timeline_idx" ON "audit_events"("correlation_id", "recorded_sequence" DESC, "id" DESC);
CREATE INDEX "audit_events_action_timeline_idx" ON "audit_events"("action_code", "recorded_sequence" DESC, "id" DESC);
CREATE INDEX "audit_events_recorded_time_idx" ON "audit_events"("recorded_at" DESC, "recorded_sequence" DESC);

CREATE TABLE "audit_event_links" (
  "audit_event_id" UUID NOT NULL,
  "target_type" VARCHAR(80) NOT NULL,
  "target_id" VARCHAR(200) NOT NULL,
  "relationship_type" VARCHAR(80) NOT NULL,
  PRIMARY KEY ("audit_event_id", "target_type", "target_id"),
  CONSTRAINT "audit_event_links_event_fkey" FOREIGN KEY ("audit_event_id") REFERENCES "audit_events"("id") ON DELETE RESTRICT,
  CONSTRAINT "audit_event_links_target_check" CHECK ("target_type" ~ '^[A-Z][A-Z0-9_]*$' AND "target_id" = btrim("target_id") AND length("target_id") > 0),
  CONSTRAINT "audit_event_links_relationship_check" CHECK ("relationship_type" ~ '^[A-Z][A-Z0-9_]*$')
);

CREATE INDEX "audit_event_links_target_idx" ON "audit_event_links"("target_type", "target_id", "audit_event_id");

CREATE FUNCTION "reject_audit_history_mutation"() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'audit history is append-only' USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER "audit_events_append_only" BEFORE UPDATE OR DELETE ON "audit_events"
FOR EACH ROW EXECUTE FUNCTION "reject_audit_history_mutation"();

CREATE TRIGGER "audit_event_links_append_only" BEFORE UPDATE OR DELETE ON "audit_event_links"
FOR EACH ROW EXECUTE FUNCTION "reject_audit_history_mutation"();

INSERT INTO "capabilities" ("id", "code", "description") VALUES
  ('10000000-0000-4000-8000-000000000014', 'audit.event.read', 'Read exact scoped append-only audit evidence');
